/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/initDB`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Launch)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Launch)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Launch)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/[Main page]`, params: Router.UnknownInputParams & { Main page: string | number; } } | { pathname: `/[Main page]/Progress`, params: Router.UnknownInputParams & { Main page: string | number; } } | { pathname: `/[Main page]/Settings`, params: Router.UnknownInputParams & { Main page: string | number; } } | { pathname: `/[Main page]/Settings/prefrences`, params: Router.UnknownInputParams & { Main page: string | number; } } | { pathname: `/[Main page]/Settings/settingsSubmenuPlaceholder`, params: Router.UnknownInputParams & { Main page: string | number; } } | { pathname: `/[Main page]/Tasks`, params: Router.UnknownInputParams & { Main page: string | number; } } | { pathname: `/[Main page]/Tasks/progress`, params: Router.UnknownInputParams & { Main page: string | number; } } | { pathname: `/[Main page]/Tasks/update`, params: Router.UnknownInputParams & { Main page: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/initDB`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Launch)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Launch)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Launch)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/[Main page]`, params: Router.UnknownOutputParams & { Main page: string; } } | { pathname: `/[Main page]/Progress`, params: Router.UnknownOutputParams & { Main page: string; } } | { pathname: `/[Main page]/Settings`, params: Router.UnknownOutputParams & { Main page: string; } } | { pathname: `/[Main page]/Settings/prefrences`, params: Router.UnknownOutputParams & { Main page: string; } } | { pathname: `/[Main page]/Settings/settingsSubmenuPlaceholder`, params: Router.UnknownOutputParams & { Main page: string; } } | { pathname: `/[Main page]/Tasks`, params: Router.UnknownOutputParams & { Main page: string; } } | { pathname: `/[Main page]/Tasks/progress`, params: Router.UnknownOutputParams & { Main page: string; } } | { pathname: `/[Main page]/Tasks/update`, params: Router.UnknownOutputParams & { Main page: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/home${`?${string}` | `#${string}` | ''}` | `/initDB${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(Launch)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(Launch)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(Launch)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/initDB`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Launch)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Launch)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Launch)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | `/${Router.SingleRoutePart<T>}` | `/${Router.SingleRoutePart<T>}/Progress` | `/${Router.SingleRoutePart<T>}/Settings` | `/${Router.SingleRoutePart<T>}/Settings/prefrences` | `/${Router.SingleRoutePart<T>}/Settings/settingsSubmenuPlaceholder` | `/${Router.SingleRoutePart<T>}/Tasks` | `/${Router.SingleRoutePart<T>}/Tasks/progress` | `/${Router.SingleRoutePart<T>}/Tasks/update` | { pathname: `/[Main page]`, params: Router.UnknownInputParams & { Main page: string | number; } } | { pathname: `/[Main page]/Progress`, params: Router.UnknownInputParams & { Main page: string | number; } } | { pathname: `/[Main page]/Settings`, params: Router.UnknownInputParams & { Main page: string | number; } } | { pathname: `/[Main page]/Settings/prefrences`, params: Router.UnknownInputParams & { Main page: string | number; } } | { pathname: `/[Main page]/Settings/settingsSubmenuPlaceholder`, params: Router.UnknownInputParams & { Main page: string | number; } } | { pathname: `/[Main page]/Tasks`, params: Router.UnknownInputParams & { Main page: string | number; } } | { pathname: `/[Main page]/Tasks/progress`, params: Router.UnknownInputParams & { Main page: string | number; } } | { pathname: `/[Main page]/Tasks/update`, params: Router.UnknownInputParams & { Main page: string | number; } };
    }
  }
}
